### ISSUE TITLE
可遇不可求

### ISSUE THREAD

**Issue by Tomotoes** [Tomotoes/weibo#118]
“可遇不可求” 指的是任何美好的东西只能等待，该是你的 只要通过努力抓住时机 即会得到，不该是你的 则不可强求，即使勉强得到了 也终会失去。
爱情不就是这个样子的嘛.

**Comment by wubazx** [comment]
大佬，关注你很长时间了，就今天突然点进相册，才发现你是男生，一直先入为主的以为是女生v_v

**Comment by Tomotoes** [comment]
> @wubazx
> 大佬，关注你很长时间了，就今天突然点进相册，才发现你是男生，一直先入为主的以为是女生v_v

啊这....

**Comment by Tomotoes** [comment]
> @wubazx
> 大佬，关注你很长时间了，就今天突然点进相册，才发现你是男生，一直先入为主的以为是女生v_v

hah 我头像是前女友的画图.. 感觉自己画得挺好看的, 就一直没变~ 这样..

**Comment by wubazx** [comment]
> @Tomotoes
> > @wubazx
> > 大佬，关注你很长时间了，就今天突然点进相册，才发现你是男生，一直先入为主的以为是女生v_v
> 
> hah 我头像是前女友的画图.. 感觉自己画得挺好看的, 就一直没变~ 这样..

确实是头像误导了，然后博客也是很有设计感，看文章也是感觉内心活动丰富，😀

**Comment by Tomotoes** [comment]
> @wubazx
> > @Tomotoes
> > > @wubazx
> > > 大佬，关注你很长时间了，就今天突然点进相册，才发现你是男生，一直先入为主的以为是女生v_v
> > 
> > hah 我头像是前女友的画图.. 感觉自己画得挺好看的, 就一直没变~ 这样..
> 
> 确实是头像误导了，然后博客也是很有设计感，看文章也是感觉内心活动丰富，😀

hah 谢谢你一直以来的关注, 不知对 [思考的价值](http://thinking.tomotoes.com/) 有没有兴趣~
