### ISSUE TITLE
283

### ISSUE THREAD

**Issue by Tomotoes** [Tomotoes/weibo#49]
全身心复习考研了，距离考研还有283天，加油💪

**Comment by YINAOR** [comment]
向大佬低头

**Comment by lateral404** [comment]
博主，请问一下你这个主题可以开源吗？？？好喜欢这样简洁的博客

**Comment by Tomotoes** [comment]
> 博主，请问一下你这个主题可以开源吗？？？好喜欢这样简洁的博客

曾经开源过，不过因为没有精力维护，[目前已存档](https://github.com/Tomotoes/hexo-theme-tomotoes)。
